// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SimulacaoCompra.Models;
using System;

namespace SimulacaoCompra.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    partial class BancoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimulacaoCompra.Models.Compra", b =>
                {
                    b.Property<int>("Idcompra")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Datacompra");

                    b.Property<decimal>("Qtdparcelas")
                        .HasColumnType("Decimal(10,5)");

                    b.Property<string>("TipoCalculo");

                    b.Property<decimal>("Valorjuros")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("Valorparcela")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Valortotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Idcompra");

                    b.ToTable("Compras");
                });
#pragma warning restore 612, 618
        }
    }
}
